### ISSUE TITLE
Add a README so new people can understand what this does!

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/abq-financial-services-directory#1]

**Comment by mapsam** [comment]
![idontgetit](https://cloud.githubusercontent.com/assets/1943001/8559100/290b8b6c-24be-11e5-8184-0da19ebd6c37.gif)

**Comment by boonrs** [comment]
:pray: Kindness to new people! :hibiscus:

**Comment by tmaybe** [comment]
![14gwp](https://cloud.githubusercontent.com/assets/546665/8626144/cc75b2e2-26f7-11e5-8478-f91cffa23a6e.gif)
